### ISSUE TITLE
Virtualspace showing wrong background on different virtual desktop.

### ISSUE THREAD

**Issue by bigplayer-ai** [newlooper/VirtualSpace#41]
Hey,
Virtualspace is showing wrong background on different virtual desktop as shown in the images below:
What shows in win + tab:
![image](https://user-images.githubusercontent.com/119108387/219942102-fed66719-94db-4d3f-aa73-d8a2a00b9046.png)
Real/expected image:
![image](https://user-images.githubusercontent.com/119108387/219942134-0a1f31dd-fb41-4230-977c-46f13e0346ff.png)

**Comment by newlooper** [comment]
delete `Cache` folder and restart VirtualSpace.

**Comment by bigplayer-ai** [comment]
> delete `Cache` folder and restart VirtualSpace. note: VirtualSpace use Windows Wallpaper, not thirdparty software like `Wallpaper Engine`

Yes I have windows wallpaper changing every hour and virtualspace seems not updating its wallpaper values in virtual desktops.
look at this:
https://imgur.com/uBhzUhk
![Clip_20230220_173249](https://user-images.githubusercontent.com/119108387/220147580-5c2375c8-03b3-4e37-8502-4e4bd7a5370e.png)

![Clip_20230220_173249](https://user-images.githubusercontent.com/119108387/220147528-728aaaec-982e-4e6d-b71c-182d62a23728.png)

**Comment by newlooper** [comment]
The pictures in slideshow mode do not belong to any virtual desktop, and Windows switches wallpapers by overwriting the same path file, thus achieving the slideshow effect.

In Win11, with picture mode wallpapers, each virtual desktop has a separate wallpaper path, so each virtual desktop can display a different wallpaper.

Although VirtualSpace can update the background of virtual desktops in the MainView by detecting changes in the slideshow file, all virtual desktops must be updated to the same background (because the file path remains the same), which is contrary to the original design of VirtualSpace.

I personally use Wallpaper Engine as a dynamic wallpaper, which causes the virtual desktop background in the MainView to be different from the actual desktop wallpaper, but, compared to its position and name in the MainView, the background of virtual desktop only provides an aid to distinguish between different virtual desktops, and there is no rigid need to correspond to the actual desktop, and in most cases, the virtual desktop backgrounds in the MainView are blocked by window thumbnails.

VirtualSpace is focused on managing the windows in the virtual desktop, not the background management of the virtual desktop, after all, when the MainView is rising, if there are no windows, only a preview of the virtual desktop, what is the practical significance of it.

**Comment by bigplayer-ai** [comment]
> The pictures in slideshow mode do not belong to any virtual desktop, and Windows switches wallpapers by overwriting the same path file, thus achieving the slideshow effect.
> 
> In Win11, with picture mode wallpapers, each virtual desktop has a separate wallpaper path, so each virtual desktop can display a different wallpaper.
> 
> Although VirtualSpace can update the background of virtual desktops in the MainView by detecting changes in the slideshow file, all virtual desktops must be updated to the same background (because the file path remains the same), which is contrary to the original design of VirtualSpace.
> 
> I personally use Wallpaper Engine as a dynamic wallpaper, which causes the virtual desktop background in the MainView to be different from the actual desktop wallpaper, but, compared to its position and name in the MainView, the background of virtual desktop only provides an aid to distinguish between different virtual desktops, and there is no rigid need to correspond to the actual desktop, and in most cases, the virtual desktop backgrounds in the MainView are blocked by window thumbnails.
> 
> VirtualSpace is focused on managing the windows in the virtual desktop, not the background management of the virtual desktop, after all, when the MainView is rising, if there are no windows, only a preview of the virtual desktop, what is the practical significance of it.

Yes but my OCD kills me for this lol
I mean the wallpaper is changed why does not virtual space gets auto synced the new wallpaper?
I think virtualspace needs to be reloaded or something.

**Comment by newlooper** [comment]
I have made it very clear.

But it could be stated in another way: it's not a question of technical implementation, but a question of design philosophy. It can be, but it is not appropriate.

Unless VirtualSpace implements complete management of virtual desktop backgrounds on its own, which is certainly reinventing the wheel, there is too much great software on the market for wallpaper management, and that's not what VirtualSpace was designed for in the first place.

Furthermore, it would be unrealistic to make VirtualSpace compatible with all wallpaper management software.

For example: Wallpaper Engine does not support virtual desktops, only different wallpapers on different physical monitors. At this point, if the user believes that the virtual desktop background in the main view must be the same as the actual desktop, then is it better to choose VirtualSpace over Wallpaper Engine? Or should I choose Wallpaper Engine and discard VirtualSpace?

**Comment by bigplayer-ai** [comment]
But how about native windows implementation of wallpapers switch?

**Comment by newlooper** [comment]
This requires VirtualSpace to actively monitor certain files in `%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Themes\` (rude, unsafe) instead of subscribing to system notifications (friendly, safe).

i didn't like the rude way.

**Comment by bigplayer-ai** [comment]
> This requires VirtualSpace to actively monitor certain files in `%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Themes\` (rude, unsafe) instead of subscribing to system notifications (friendly, safe).
> 
> i didn't like the rude way.

I think monitoring the files there is a better option. As it hinders a functionality of the application to show the real current desktop wallpaper (this is a mess up visually).
